# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://simonpercic.github.io
title: Simon Percic
email: simon@percic.si
author: Simon Percic
description: > # "Write an awesome description for your new site here.
  Simon Percic
  Engineering Manager
  Passionate about technology, learning, growth, self-improvement, and coaching.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: linkedin
    url: https://www.linkedin.com/in/simonpercic
  - title: github
    url: https://github.com/simonpercic
  - title: twitter
    url: https://twitter.com/simonpercic
  - title: medium
    url: https://medium.com/@simonpercic

contact:
  - title: email
    icon: envelope
    url: mailto:simon@percic.si
