# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://simonpercic.github.io
title: Simon Perčič
email: simon@percic.si
author: Simon Perčič
description: > # "Write an awesome description for your new site here. 
  Simon Perčič 
  Android software engineer with years of working experience.
  Full-cycle development, from the concept and project specifications to final production-ready code and support."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/simonpercic
  - title: twitter
    url: https://twitter.com/simonpercic
  - title: linkedin
    url: https://www.linkedin.com/in/simonpercic

contact:
  - title: skype
    url: skype:simon-percic
